// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa4MRhQZwQ8jLk6CfXiUH7uDJZCcQUekI',
    appId: '1:710264886776:web:cf30b0ac00c6d0f26c720d',
    messagingSenderId: '710264886776',
    projectId: 'easy2-94537',
    authDomain: 'easy2-94537.firebaseapp.com',
    storageBucket: 'easy2-94537.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw2IP5fTeBW3rwnHOdDqzE98H806oqpX0',
    appId: '1:710264886776:android:b4afda058655e7856c720d',
    messagingSenderId: '710264886776',
    projectId: 'easy2-94537',
    storageBucket: 'easy2-94537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqkkr7RIm-TpA2HYYCa1Czs47XK1vVaz8',
    appId: '1:710264886776:ios:c97be985c06dd57e6c720d',
    messagingSenderId: '710264886776',
    projectId: 'easy2-94537',
    storageBucket: 'easy2-94537.firebasestorage.app',
    iosBundleId: 'com.example.ab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqkkr7RIm-TpA2HYYCa1Czs47XK1vVaz8',
    appId: '1:710264886776:ios:c97be985c06dd57e6c720d',
    messagingSenderId: '710264886776',
    projectId: 'easy2-94537',
    storageBucket: 'easy2-94537.firebasestorage.app',
    iosBundleId: 'com.example.ab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa4MRhQZwQ8jLk6CfXiUH7uDJZCcQUekI',
    appId: '1:710264886776:web:e5eb959d5991371c6c720d',
    messagingSenderId: '710264886776',
    projectId: 'easy2-94537',
    authDomain: 'easy2-94537.firebaseapp.com',
    storageBucket: 'easy2-94537.firebasestorage.app',
  );
}
